#PARAMETROS entrenamiento.py y test.py

numEpochs:
  coarseLoc: 5
  fineLoc: 5
  globalLoc: 5 #5
epochLength:
  coarseLoc: 50000
  fineLoc: 10000
  globalLoc: 50000 #50000

thresholds:
  fineLoc:
    rPos: 0.3
    rNeg: 0.3
  globalLoc:
    rPos: 0.3
    rNeg: 0.3

losses:
  losses: ['triplet loss', 'lifted embedding', 'lazy triplet', 'semi hard',
               'batch hard', 'circle loss', 'angular loss']
  coarseLoc: ['triplet loss', 'semi hard', 'angular loss']
  fineLoc: ['triplet loss', 'semi hard', 'angular loss']
  globalLoc: ['triplet loss', 'semi hard', 'angular loss']
  abreviations: ['TL', 'LE', 'LT', 'SH', 'BH', 'CL', 'AL']


# loss order: triplet loss, lifted embedding, lazy triplet, semi hard, batch hard, circle loss, angular loss
margins:
  coarseLoc:  [[1.25], [0.25], [1.25], [1], [0.75], [0], [30]]
  fineLoc: [1.25, 0.25, 1.25, 1, 0.75, 0, 30]
  globalLoc: [[1], [0.25], [1.25], [1.25], [0.75], [1], [30]]


showLoss: 100
doValidation: 100

k:
  fineLoc: 20
  globalLoc: 20

