device: "cuda:0"

csvDir: 'CSV'
figuresDir: 'FIGURES'
datasetDir: '/home/arvc/Marcos/INVESTIGACION/DATASETS/'
modelsDir: '/home/arvc/Marcos/INVESTIGACION/TripletNetworks_GitHub/SAVED_MODELS'

testEnv: "FR_A"
envs: ["SA_B", "SA_A", "FR_B", "FR_A"]

epochLength_coarseLoc: 160
epochLength_fineLoc: 160
epochLength_globalLoc: 160
sameProbability: 0.6


losses: ["triplet loss", "lifted embedding", "lazy triplet", "semi hard",
         "batch hard", "circle loss", "angular loss", "contrastive loss"]
selectedLosses: ["triplet loss", "lifted embedding", "lazy triplet", "semi hard",
                 "batch hard", "circle loss", "angular loss", "contrastive loss"]
lossAbreviations: ["TL", "LE", "LT", "SH", "BH", "CL", "AL", "SNN"]

marginsCoarseLoc: [[1.25], [0.25], [1.25], [1], [0.75], [0], [30], [2]]
marginsFineLoc: [1.25, 0.25, 1.25, 1, 0.75, 0, 30, 2]
marginsGlobalLoc: [[1], [0.25], [1], [1.25], [1], [0.25], [30], [2]]

batchSize: 16

numEpochs: 1
numIterations: 5

numModelsSaved: 50
margin: 0.25

rPos: 0.3
rNeg: 0.3

kMax: 20

occlusionValues: [16, 32, 64, 128]
noiseValues: [5, 10, 15, 20]
blurValues: [1, 3, 5, 7]

lossExp2: "SNN"
marginExp2: 2
